/**
 * FrmLobby.java creado el 19/09/2023.
 */
package org.itson.proyectoarquitecturadominoacm.UI;

import javax.swing.ImageIcon;
import org.itson.proyectoarquitecturadominoacm.logicaAplicacion.logicaAplicacion;

/**
 *
 * @author Gabriel Mancinas,Julio Chon,Luis Ayon
 */
public class FrmLobby extends javax.swing.JFrame {
    private logicaAplicacion lAplicacion;
    /**
     * Creates new form FrmLobby
     */
    public FrmLobby(logicaAplicacion lAplicacion) {
        this.lAplicacion = lAplicacion;
        
        initComponents();
        lAplicacion.dibujarUsuario(lblApodo, lblAvatar);
        this.setVisible(true);
        this.setSize(750, 540); //736 x 500
        setIconImage(new ImageIcon(getClass().getResource("/imgFrmPrincipal/iconoGeneral.png")).getImage());
        setTitle("Dominó");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        btnListo = new javax.swing.JButton();
        lblApodo = new javax.swing.JLabel();
        lblAvatar = new javax.swing.JLabel();
        lblSlots = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(736, 500));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(736, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgIconosGenerales/iconoRegresar.png"))); // NOI18N
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 100, 80));

        btnListo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgFrmLobby/iconoListo.png"))); // NOI18N
        btnListo.setBorderPainted(false);
        btnListo.setContentAreaFilled(false);
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });
        jPanel1.add(btnListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 190, 70));

        lblApodo.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 18)); // NOI18N
        lblApodo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApodo.setText("jLabel1");
        jPanel1.add(lblApodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 120, -1));
        jPanel1.add(lblAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 150, 140));

        lblSlots.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgFrmLobby/iconoSlots.png"))); // NOI18N
        lblSlots.setMaximumSize(new java.awt.Dimension(700, 500));
        lblSlots.setMinimumSize(new java.awt.Dimension(700, 500));
        jPanel1.add(lblSlots, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 690, 240));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgFrmLobby/imgFondoLobby.png"))); // NOI18N
        lblFondo.setMaximumSize(new java.awt.Dimension(700, 500));
        lblFondo.setMinimumSize(new java.awt.Dimension(700, 500));
        lblFondo.setOpaque(true);
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
        FrmMenu frmMenu = new FrmMenu(lAplicacion);
        this.setVisible(false);
    }//GEN-LAST:event_btnListoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListo;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApodo;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblSlots;
    // End of variables declaration//GEN-END:variables
}
