/**
 * FrmLobby.java creado el 19/09/2023.
 */
package org.itson.proyectoarquitecturadominoacm.UI;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import static org.itson.proyectoarquitecturadominoacm.ProyectoArquitecturaDominoACM.mediador;

/**
 *
 * @author Gabriel Mancinas,Julio Chon,Luis Ayon
 */
public class FrmLobby extends javax.swing.JFrame {
    /**
     * Creates new form FrmLobby
     */
    public FrmLobby() {
        initComponents();
        this.setSize(750, 540); //736 x 500
        setIconImage(new ImageIcon(getClass().getResource("/imgFrmPrincipal/iconoGeneral.png")).getImage());
        asignarInformacionJugadores();
    }
    public void asignarInformacionJugadores(){
    Icon icon;
    icon = new ImageIcon(mediador.getJugador().getAvatar().getImage().getScaledInstance(lblAvatarP1.getWidth(), lblAvatarP1.getHeight(), Image.SCALE_DEFAULT));
    lblAvatarP1.setIcon(icon);
    lblNombreJugadorP1.setText(mediador.getJugador().getNombre());
    lblNombreJugadorP1.setHorizontalAlignment(SwingConstants.CENTER);
    }
    public int obtenerNumFichas(){
        String numFichas = cbxFichasPorJugador.getSelectedItem().toString();
        return Integer.parseInt(numFichas);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnFondo = new javax.swing.JPanel();
        cbxFichasPorJugador = new javax.swing.JComboBox<>();
        btnRegresar = new javax.swing.JButton();
        btnListo = new javax.swing.JButton();
        lblNombreJugadorP1 = new javax.swing.JLabel();
        lblAvatarP1 = new javax.swing.JLabel();
        lblSlots = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dominó");
        setMaximumSize(new java.awt.Dimension(755, 540));
        setMinimumSize(new java.awt.Dimension(755, 540));
        setPreferredSize(new java.awt.Dimension(755, 540));
        setResizable(false);

        jpnFondo.setBackground(new java.awt.Color(255, 0, 0));
        jpnFondo.setMinimumSize(new java.awt.Dimension(736, 500));
        jpnFondo.setOpaque(false);
        jpnFondo.setPreferredSize(new java.awt.Dimension(736, 500));
        jpnFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxFichasPorJugador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7" }));
        jpnFondo.add(cbxFichasPorJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 150, -1));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgIconosGenerales/iconoRegresar.png"))); // NOI18N
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgIconosGenerales/iconoRegresar_2.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jpnFondo.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 100, 80));

        btnListo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgFrmLobby/iconoListo.png"))); // NOI18N
        btnListo.setBorderPainted(false);
        btnListo.setContentAreaFilled(false);
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });
        jpnFondo.add(btnListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 190, 70));

        lblNombreJugadorP1.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 18)); // NOI18N
        lblNombreJugadorP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpnFondo.add(lblNombreJugadorP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 130, 30));
        jpnFondo.add(lblAvatarP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 130, 110));

        lblSlots.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgFrmLobby/iconoSlots.png"))); // NOI18N
        lblSlots.setMaximumSize(new java.awt.Dimension(700, 500));
        lblSlots.setMinimumSize(new java.awt.Dimension(700, 500));
        jpnFondo.add(lblSlots, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 690, 240));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgFrmLobby/imgFondoLobby.png"))); // NOI18N
        lblFondo.setMaximumSize(new java.awt.Dimension(700, 500));
        lblFondo.setMinimumSize(new java.awt.Dimension(755, 540));
        lblFondo.setOpaque(true);
        lblFondo.setPreferredSize(new java.awt.Dimension(755, 540));
        jpnFondo.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
    this.setVisible(false);
    mediador.getJugador().setFichas(null);
    mediador.crearPartida(mediador.getJugador(),obtenerNumFichas());
    mediador.abrirPantallaPartida();
    }//GEN-LAST:event_btnListoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
    this.setVisible(false);
    mediador.abrirPantallaMenu();
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListo;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbxFichasPorJugador;
    private javax.swing.JPanel jpnFondo;
    private javax.swing.JLabel lblAvatarP1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNombreJugadorP1;
    private javax.swing.JLabel lblSlots;
    // End of variables declaration//GEN-END:variables
}
