/**
 * FrmPrincipal.java creado el 19/09/2023.
 */
package org.itson.proyectoarquitecturadominoacm.UI;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.itson.proyectoarquitecturadominoacm.Utileria.AvatarControlador;
import org.itson.proyectoarquitecturadominoacm.Utileria.AvatarModelo;
import org.itson.proyectoarquitecturadominoacm.Utileria.AvatarVista;
import org.itson.proyectoarquitecturadominoacm.Utileria.Avatar;

/**
 *
 * @author Gabriel Mancinas
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private Avatar avatar;
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {  
        initComponents();
        this.setVisible(true);
        setIconImage(new ImageIcon(getClass().getResource("/imgFrmPrincipal/iconoGeneral.png")).getImage());
        setTitle("Dominó");
        avatar = new Avatar(btnCambiarAvatar, jPanel1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCambiarAvatar = new javax.swing.JButton();
        txtApodo = new javax.swing.JTextField();
        btnJugar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(736, 500));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(736, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCambiarAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgFrmPrincipal/iconoCambiarAvatar.png"))); // NOI18N
        btnCambiarAvatar.setBorderPainted(false);
        btnCambiarAvatar.setContentAreaFilled(false);
        jPanel1.add(btnCambiarAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 130, 130));

        txtApodo.setBackground(new java.awt.Color(227, 25, 55));
        txtApodo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        txtApodo.setForeground(new java.awt.Color(255, 255, 255));
        txtApodo.setBorder(null);
        txtApodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApodoActionPerformed(evt);
            }
        });
        jPanel1.add(txtApodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 350, 30));

        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgFrmPrincipal/iconoJugar.png"))); // NOI18N
        btnJugar.setBorderPainted(false);
        btnJugar.setContentAreaFilled(false);
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        jPanel1.add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 140, 130));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgFrmPrincipal/fondoFrmPrincipal.png"))); // NOI18N
        lblFondo.setMaximumSize(new java.awt.Dimension(700, 500));
        lblFondo.setMinimumSize(new java.awt.Dimension(700, 500));
        lblFondo.setOpaque(true);
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtApodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApodoActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        FrmMenu frmMenu = new FrmMenu();
        this.setVisible(false);
    }//GEN-LAST:event_btnJugarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarAvatar;
    private javax.swing.JButton btnJugar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField txtApodo;
    // End of variables declaration//GEN-END:variables
}
