/**
 * FrmLobby.java creado el 19/09/2023.
 */
package org.itson.proyectoarquitecturadominoacm.UI;

import java.awt.BorderLayout;
import java.awt.ComponentOrientation;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.SwingConstants;
import org.itson.proyectoarquitecturadominoacm.Fichas.Ficha;
import org.itson.proyectoarquitecturadominoacm.Fichas.FichaModelo;
import org.itson.proyectoarquitecturadominoacm.Fichas.FichaVista;
import org.itson.proyectoarquitecturadominoacm.Jugador.Jugador;
import org.itson.proyectoarquitecturadominoacm.Partida.Partida;
import org.itson.proyectoarquitecturadominoacm.Pozo.Pozo;
import static org.itson.proyectoarquitecturadominoacm.ProyectoArquitecturaDominoACM.mediador;
import org.itson.proyectoarquitecturadominoacm.Tablero.Tablero;

/**
 *
 * @author Gabriel Mancinas,Julio Chon,Luis Ayon
 */
public class FrmPartida extends javax.swing.JFrame {
    
    /**
     * Creates new form FrmLobby
     */
    public FrmPartida() {
        
        initComponents();
        //this.setSize(850, 575); //800 x 550
        this.setLayout(new BorderLayout());
        this.pack();
        
        setIconImage(new ImageIcon(getClass().getResource("/imgFrmPrincipal/iconoGeneral.png")).getImage());
        this.crearPartida();
        this.setearInformacionJugador();
        mediador.getJugador().setPanelFichas(jpnFichas);
        mediador.getPartida().repartirFichas();
        setFocusable(true);
        requestFocusInWindow();
        
        scrollPanel.getHorizontalScrollBar().setValue((scrollPanel.getHorizontalScrollBar().getMaximum() - scrollPanel.getHorizontalScrollBar().getVisibleAmount())/2);
        
    }
    public void setearInformacionJugador(){
    Icon icon;
    icon = new ImageIcon(mediador.getJugador().getAvatar().getImage().getScaledInstance(lblAvatar.getWidth(), lblAvatar.getHeight(), Image.SCALE_DEFAULT));
    lblAvatar.setIcon(icon);
    lblNombreJugador.setText(mediador.getJugador().getNombre());
    lblNombreJugador.setHorizontalAlignment(SwingConstants.CENTER);
    }
    public void crearPartida(){
    Pozo pozo = new Pozo(btnPozo);
    Tablero tablero = new Tablero(jpnTablero);    
    mediador.getPartida().setPozo(pozo);
    mediador.getPartida().setTablero(tablero);
    mediador.getPartida().suscribirse();
    }
    public void acabarPartida()
    {
        mediador.abrirPantallaMenu();
        this.dispose();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnFondo = new javax.swing.JPanel();
        scrollPanel = new javax.swing.JScrollPane();
        jpnTablero = new javax.swing.JPanel();
        jpnFichas = new javax.swing.JPanel();
        lblNombreJugador = new javax.swing.JLabel();
        lblAvatar = new javax.swing.JLabel();
        btnAcabarPartida = new javax.swing.JButton();
        btnPozo = new javax.swing.JButton();
        lblTableroFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("¡Partida en curso!");
        setMaximumSize(new java.awt.Dimension(800, 550));
        setMinimumSize(new java.awt.Dimension(800, 550));
        setPreferredSize(new java.awt.Dimension(800, 550));
        setSize(new java.awt.Dimension(800, 550));

        jpnFondo.setMaximumSize(new java.awt.Dimension(800, 550));
        jpnFondo.setMinimumSize(new java.awt.Dimension(800, 550));
        jpnFondo.setPreferredSize(new java.awt.Dimension(800, 550));
        jpnFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollPanel.setBorder(null);
        scrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jpnTablero.setBackground(new java.awt.Color(8, 78, 171));
        jpnTablero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpnTablero.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        javax.swing.GroupLayout jpnTableroLayout = new javax.swing.GroupLayout(jpnTablero);
        jpnTablero.setLayout(jpnTableroLayout);
        jpnTableroLayout.setHorizontalGroup(
            jpnTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1201, Short.MAX_VALUE)
        );
        jpnTableroLayout.setVerticalGroup(
            jpnTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );

        scrollPanel.setViewportView(jpnTablero);

        jpnFondo.add(scrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 368, 260));

        jpnFichas.setBackground(new java.awt.Color(8, 78, 171));
        jpnFichas.setLayout(null);
        jpnFondo.add(jpnFichas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 368, 88));

        lblNombreJugador.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jpnFondo.add(lblNombreJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 130, 20));
        jpnFondo.add(lblAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 100, 90));

        btnAcabarPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgFrmPartida/iconoAcabarPartida.png"))); // NOI18N
        btnAcabarPartida.setBorderPainted(false);
        btnAcabarPartida.setContentAreaFilled(false);
        btnAcabarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcabarPartidaActionPerformed(evt);
            }
        });
        jpnFondo.add(btnAcabarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, 180, 60));

        btnPozo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgFrmPartida/iconoTomarFicha.png"))); // NOI18N
        btnPozo.setBorderPainted(false);
        btnPozo.setContentAreaFilled(false);
        jpnFondo.add(btnPozo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 180, 70));

        lblTableroFondo.setBackground(new java.awt.Color(1, 114, 171));
        lblTableroFondo.setAlignmentY(0.0F);
        lblTableroFondo.setMaximumSize(new java.awt.Dimension(800, 550));
        lblTableroFondo.setMinimumSize(new java.awt.Dimension(800, 550));
        lblTableroFondo.setOpaque(true);
        lblTableroFondo.setPreferredSize(new java.awt.Dimension(800, 550));
        jpnFondo.add(lblTableroFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcabarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcabarPartidaActionPerformed
        
        this.dispose();
        mediador.abrirPantallaMenu();
    }//GEN-LAST:event_btnAcabarPartidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcabarPartida;
    private javax.swing.JButton btnPozo;
    private javax.swing.JPanel jpnFichas;
    private javax.swing.JPanel jpnFondo;
    private javax.swing.JPanel jpnTablero;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblNombreJugador;
    private javax.swing.JLabel lblTableroFondo;
    private javax.swing.JScrollPane scrollPanel;
    // End of variables declaration//GEN-END:variables

}
