/**
 * FrmPrincipal.java creado el 19/09/2023.
 */
package org.itson.proyectoarquitecturadominoacm.UI;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.itson.proyectoarquitecturadominoacm.Jugador.Jugador;
import org.itson.proyectoarquitecturadominoacm.Mediador.IMediador;
import static org.itson.proyectoarquitecturadominoacm.ProyectoArquitecturaDominoACM.mediador;
import org.itson.proyectoarquitecturadominoacm.Utileria.AvatarControlador;
import org.itson.proyectoarquitecturadominoacm.Utileria.AvatarModelo;
import org.itson.proyectoarquitecturadominoacm.Utileria.AvatarVista;
import org.itson.proyectoarquitecturadominoacm.Utileria.Avatar;


/**
 *
 * @author Gabriel Mancinas,Julio Chon,Luis Ayon
 */
public class FrmPrincipal extends javax.swing.JFrame {
    private String nombreJugador;
    private ImageIcon avatarJugador;
    private Avatar avatar;
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {  
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imgFrmPrincipal/iconoGeneral.png")).getImage());
        setTitle("Dominó");
        avatar = new Avatar(btnCambiarAvatar, jpnGeneral);
    }
    public void obtenerDatosJugador(){
        nombreJugador = txtApodo.getText();
        avatarJugador = avatar.getAvatar();
    }
    public void registrarJugador(){
    mediador.getJugador().setNombre(nombreJugador);
    mediador.getJugador().setAvatar(avatarJugador);
    }
    public boolean validarNombre(){
    return nombreJugador.isBlank();
    }
    public boolean validarAvatar(){
    return avatarJugador.getImage()==null;
    }
    public void mostrarMensaje(String mensaje){
    JOptionPane.showMessageDialog(this,mensaje, "Advertencia", JOptionPane.WARNING_MESSAGE);
    }
    public Boolean validar(){
    if((validarNombre() || validarAvatar())){
        mostrarMensaje("Debes de tener al menos un avatar seleccionado y un nombre");
        return false;
    }
    return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnGeneral = new javax.swing.JPanel();
        btnCambiarAvatar = new javax.swing.JButton();
        txtApodo = new javax.swing.JTextField();
        btnJugar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jpnGeneral.setBackground(new java.awt.Color(255, 0, 0));
        jpnGeneral.setMinimumSize(new java.awt.Dimension(736, 500));
        jpnGeneral.setOpaque(false);
        jpnGeneral.setPreferredSize(new java.awt.Dimension(736, 500));
        jpnGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCambiarAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgFrmPrincipal/iconoCambiarAvatar.png"))); // NOI18N
        btnCambiarAvatar.setBorderPainted(false);
        btnCambiarAvatar.setContentAreaFilled(false);
        btnCambiarAvatar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgFrmPrincipal/iconoCambiarAvatar_2.png"))); // NOI18N
        btnCambiarAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarAvatarActionPerformed(evt);
            }
        });
        jpnGeneral.add(btnCambiarAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 130, 130));

        txtApodo.setBackground(new java.awt.Color(227, 25, 55));
        txtApodo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        txtApodo.setForeground(new java.awt.Color(255, 255, 255));
        txtApodo.setBorder(null);
        txtApodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApodoActionPerformed(evt);
            }
        });
        txtApodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApodoKeyTyped(evt);
            }
        });
        jpnGeneral.add(txtApodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 350, 30));

        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgFrmPrincipal/iconoJugar_2.png"))); // NOI18N
        btnJugar.setBorderPainted(false);
        btnJugar.setContentAreaFilled(false);
        btnJugar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgFrmPrincipal/iconoJugar.png"))); // NOI18N
        btnJugar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnJugar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        jpnGeneral.add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 190, 150));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgFrmPrincipal/imgFondoPrincipal.png"))); // NOI18N
        lblFondo.setMaximumSize(new java.awt.Dimension(700, 500));
        lblFondo.setMinimumSize(new java.awt.Dimension(700, 500));
        lblFondo.setOpaque(true);
        jpnGeneral.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    private void txtApodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApodoActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
    obtenerDatosJugador();
        if(!validar()){
        return;
    }
    registrarJugador();
    this.setVisible(false);
    mediador.abrirPantallaMenu();
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnCambiarAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarAvatarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiarAvatarActionPerformed

    private void txtApodoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApodoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApodoKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarAvatar;
    private javax.swing.JButton btnJugar;
    private javax.swing.JPanel jpnGeneral;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField txtApodo;
    // End of variables declaration//GEN-END:variables
}
